on: pull_request_target

name: "Dependabot: auto-merge patch versions"

jobs:
  approve-dependabot-pr:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge Dependabot PRs for patch versions
        if: ${{github.event.workflow_run.conclusion == 'success' && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        uses: ridedott/merge-me-action@d3bbf4ca8af389466cde33b9b7df5359cc84188c # v2.10.145
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
